<?php

declare(strict_types=1);

require __DIR__ . '/../src/Bootstrap.php';

use DuelDesk\Controllers\HomeController;
use DuelDesk\Controllers\AuthController;
use DuelDesk\Controllers\AdminController;
use DuelDesk\Controllers\AdminGameController;
use DuelDesk\Controllers\AdminLanEventController;
use DuelDesk\Controllers\AdminRulesetController;
use DuelDesk\Controllers\AdminTournamentController;
use DuelDesk\Controllers\AccountController;
use DuelDesk\Controllers\LanEventController;
use DuelDesk\Controllers\LanSignupController;
use DuelDesk\Controllers\PickBanController;
use DuelDesk\Controllers\MatchReportController;
use DuelDesk\Controllers\TournamentController;
use DuelDesk\Controllers\TournamentSignupController;
use DuelDesk\Controllers\TournamentTeamController;
use DuelDesk\Controllers\TeamController;
use DuelDesk\Controllers\TeamMatchController;
use DuelDesk\Controllers\MultiRoundController;
use DuelDesk\Controllers\BotApiController;
use DuelDesk\Http\Router;

$router = new Router();

$router->get('/', [HomeController::class, 'index']);

$router->get('/register', [AuthController::class, 'register']);
$router->post('/register', [AuthController::class, 'registerPost']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'loginPost']);
$router->post('/logout', [AuthController::class, 'logout']);

$router->get('/account', [AccountController::class, 'index']);
$router->get('/account/discord/connect', [AccountController::class, 'discordConnect']);
$router->get('/account/discord/callback', [AccountController::class, 'discordCallback']);
$router->post('/account/discord/disconnect', [AccountController::class, 'discordDisconnect']);

$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/users', [AdminController::class, 'users']);
$router->post('/admin/users/{id:\\d+}/role', [AdminController::class, 'updateRole']);
$router->post('/admin/users/{id:\\d+}/delete', [AdminController::class, 'deleteUser']);
$router->get('/admin/games', [AdminGameController::class, 'index']);
$router->post('/admin/games', [AdminGameController::class, 'create']);
$router->get('/admin/games/{id:\\d+}', [AdminGameController::class, 'edit']);
$router->post('/admin/games/{id:\\d+}', [AdminGameController::class, 'update']);
$router->post('/admin/games/{id:\\d+}/delete', [AdminGameController::class, 'delete']);
$router->get('/admin/lan', [AdminLanEventController::class, 'index']);
$router->get('/admin/lan/new', [AdminLanEventController::class, 'new']);
$router->post('/admin/lan', [AdminLanEventController::class, 'create']);
$router->get('/admin/lan/{id:\\d+}', [AdminLanEventController::class, 'edit']);
$router->post('/admin/lan/{id:\\d+}', [AdminLanEventController::class, 'update']);
$router->post('/admin/lan/{id:\\d+}/tournaments/attach', [AdminLanEventController::class, 'attachTournament']);
$router->post('/admin/lan/{id:\\d+}/tournaments/{tournamentId:\\d+}/detach', [AdminLanEventController::class, 'detachTournament']);
$router->post('/admin/lan/{id:\\d+}/delete', [AdminLanEventController::class, 'delete']);
$router->get('/admin/rulesets', [AdminRulesetController::class, 'index']);
$router->get('/admin/rulesets/new', [AdminRulesetController::class, 'new']);
$router->post('/admin/rulesets', [AdminRulesetController::class, 'create']);
$router->get('/admin/rulesets/{id:\\d+}', [AdminRulesetController::class, 'edit']);
$router->post('/admin/rulesets/{id:\\d+}', [AdminRulesetController::class, 'update']);
$router->post('/admin/rulesets/{id:\\d+}/delete', [AdminRulesetController::class, 'delete']);
$router->get('/admin/tournaments/{id:\\d+}', [AdminTournamentController::class, 'show']);
$router->post('/admin/tournaments/{id:\\d+}/config', [AdminTournamentController::class, 'updateConfig']);
$router->post('/admin/tournaments/{id:\\d+}/settings', [AdminTournamentController::class, 'updateSettings']);
$router->post('/admin/tournaments/{id:\\d+}/ruleset', [AdminTournamentController::class, 'updateRuleset']);
$router->post('/admin/tournaments/{id:\\d+}/delete', [AdminTournamentController::class, 'deleteTournament']);
$router->post('/admin/tournaments/{id:\\d+}/bracket/generate', [AdminTournamentController::class, 'generateBracket']);
$router->post('/admin/tournaments/{id:\\d+}/bracket/reset', [AdminTournamentController::class, 'resetBracket']);
$router->post('/admin/tournaments/{id:\\d+}/matches/{matchId:\\d+}/report', [AdminTournamentController::class, 'reportMatch']);
$router->post('/admin/tournaments/{id:\\d+}/matches/{matchId:\\d+}/report/reject', [AdminTournamentController::class, 'rejectReport']);
$router->post('/admin/tournaments/{id:\\d+}/matches/{matchId:\\d+}/schedule', [AdminTournamentController::class, 'scheduleMatch']);
$router->post('/admin/tournaments/{id:\\d+}/matches/{matchId:\\d+}/bestof', [AdminTournamentController::class, 'setBestOf']);
$router->post('/admin/tournaments/{id:\\d+}/players/{playerId:\\d+}/seed', [AdminTournamentController::class, 'setSeed']);
$router->post('/admin/tournaments/{id:\\d+}/players/{playerId:\\d+}/checkin', [AdminTournamentController::class, 'setCheckin']);
$router->post('/admin/tournaments/{id:\\d+}/players/{playerId:\\d+}/remove', [AdminTournamentController::class, 'removePlayer']);
$router->post('/admin/tournaments/{id:\\d+}/teams/{teamId:\\d+}/seed', [AdminTournamentController::class, 'setTeamSeed']);
$router->post('/admin/tournaments/{id:\\d+}/teams/{teamId:\\d+}/checkin', [AdminTournamentController::class, 'setTeamCheckin']);
$router->post('/admin/tournaments/{id:\\d+}/teams/{teamId:\\d+}/remove', [AdminTournamentController::class, 'removeTeam']);

$router->get('/tournaments', [TournamentController::class, 'index']);
$router->get('/tournaments/new', [TournamentController::class, 'new']);
$router->post('/tournaments', [TournamentController::class, 'create']);
$router->get('/tournaments/{id:\\d+}/live', [TournamentController::class, 'live']);
$router->get('/tournaments/{id:\\d+}/matches/{matchId:\\d+}', [TournamentController::class, 'match']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/report', [MatchReportController::class, 'report']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/team-lineup', [TeamMatchController::class, 'setLineup']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/team-duels/{duelId:\\d+}/confirm', [TeamMatchController::class, 'confirmDuel']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/rounds/add', [MultiRoundController::class, 'addRound']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/rounds/{roundId:\\d+}/delete', [MultiRoundController::class, 'deleteRound']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/rounds/finalize', [MultiRoundController::class, 'finalize']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/pickban/toss', [PickBanController::class, 'toss']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/pickban/start', [PickBanController::class, 'start']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/pickban/act', [PickBanController::class, 'act']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/pickban/side', [PickBanController::class, 'side']);
$router->post('/tournaments/{id:\\d+}/matches/{matchId:\\d+}/pickban/reset', [PickBanController::class, 'reset']);
$router->get('/tournaments/{id:\\d+}', [TournamentController::class, 'show']);
$router->get('/t/{slug:[a-z0-9-]+}', [TournamentController::class, 'showBySlug']);
$router->get('/lan', [LanEventController::class, 'index']);
$router->get('/lan/{slug:[a-z0-9-]+}', [LanEventController::class, 'showBySlug']);
$router->post('/lan/{slug:[a-z0-9-]+}/signup', [LanSignupController::class, 'signup']);
$router->post('/lan/{slug:[a-z0-9-]+}/withdraw', [LanSignupController::class, 'withdraw']);
$router->post('/lan/{slug:[a-z0-9-]+}/teams/create', [LanSignupController::class, 'createTeam']);
$router->post('/lan/{slug:[a-z0-9-]+}/teams/join', [LanSignupController::class, 'joinTeam']);
$router->post('/lan/{slug:[a-z0-9-]+}/teams/{teamId:\\d+}/leave', [LanSignupController::class, 'leaveTeam']);
$router->get('/lan/{lanSlug:[a-z0-9-]+}/t/{slug:[a-z0-9-]+}', [TournamentController::class, 'showInLan']);
$router->get('/api/bot/pickban/pending', [BotApiController::class, 'pickbanPending']);
$router->get('/api/bot/tournaments/report', [BotApiController::class, 'reportTournaments']);
$router->get('/api/bot/tournaments/{id:\\d+}/matches/report', [BotApiController::class, 'reportMatches']);
$router->post('/api/bot/matches/report', [BotApiController::class, 'reportMatch']);
$router->post('/tournaments/{id:\\d+}/signup', [TournamentSignupController::class, 'signup']);
$router->post('/tournaments/{id:\\d+}/withdraw', [TournamentSignupController::class, 'withdraw']);
$router->post('/tournaments/{id:\\d+}/teams/create', [TournamentTeamController::class, 'create']);
$router->post('/tournaments/{id:\\d+}/teams/join', [TournamentTeamController::class, 'join']);
$router->post('/tournaments/{id:\\d+}/teams/{teamId:\\d+}/leave', [TournamentTeamController::class, 'leave']);
$router->get('/teams/{id:\\d+}', [TeamController::class, 'show']);
$router->post('/teams/{id:\\d+}/rename', [TeamController::class, 'rename']);
$router->post('/teams/{id:\\d+}/members/{userId:\\d+}/kick', [TeamController::class, 'kick']);
$router->post('/teams/{id:\\d+}/members/{userId:\\d+}/captain', [TeamController::class, 'setCaptain']);

$router->dispatch($_SERVER['REQUEST_METHOD'] ?? 'GET', $_SERVER['REQUEST_URI'] ?? '/');
